In [30]:
import numpy as np

In [31]:
#initializing NumPy with zeros

In [32]:
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [33]:
type(n1)

numpy.ndarray

In [34]:
n2=np.zeros((5,5))
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
type(n2)

numpy.ndarray

In [36]:
n3=np.zeros((2,3))

In [37]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
n4=np.zeros((10,10))
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
n5=np.full((3,3),55)
n5

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [40]:
n6=np.arange(11,21)
n6

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [41]:
n7=np.arange(10,50,5)
n7

array([10, 15, 20, 25, 30, 35, 40, 45])

In [42]:
n8=np.arange(50,101)
n8

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [43]:
n9=np.arange(50,500,10)
n9

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
       310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430,
       440, 450, 460, 470, 480, 490])

In [44]:
n1 = np.random.randint(1,100,5)
n1

array([11, 33, 92, 38, 45])