In [4]:
import numpy as np
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])
np.vstack((n1, n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
n3 = np.hstack((n1, n2))

In [6]:
n3

array([1, 2, 3, 4, 5, 6])

In [7]:
n4 = np.column_stack((n1, n2))

In [8]:
n4

array([[1, 4],
       [2, 5],
       [3, 6]])