In [31]:
#BASIC SUBSTRACTION

In [27]:
#BASIC MULTIPLICATION

In [32]:
#BASIC DIVISION

In [33]:
n1 = np.array([10, 30, 50])
n1

array([10, 30, 50])

In [34]:
n1 + 5

array([15, 35, 55])

In [36]:
n1 - 5

array([ 5, 25, 45])

In [37]:
n1 * 10

array([100, 300, 500])

In [38]:
n1 / 5

array([ 2.,  6., 10.])