In [71]:
import numpy as np

In [72]:
n1=np.array([10, 20, 30])
n2=np.array([40, 50, 60])

In [74]:
#vertically stack!
np.vstack((n1, n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [2]:
#horizontly stock
import numpy as np
n1 = np.array([10, 20, 30])
n2 = np.array([40, 50, 60])

np.hstack((n1, n2))

array([10, 20, 30, 40, 50, 60])

In [3]:
# column_stack()
import numpy as np
n1=np.array([10, 20, 30])
n2=np.array([40, 50, 60])

np.column_stack((n1, n2))

array([[10, 40],
       [20, 50],
       [30, 60]])