In [9]:
# INTERSECTION & DIFFERENCE

In [10]:
import numpy as np
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90])

In [11]:
np.intersect1d(n1, n2)

array([50, 60])

In [13]:
np.setdiff1d(n1, n2)

array([10, 20, 30, 40])

In [17]:
np.setdiff1d(n2, n1)

array([70, 80, 90])

In [18]:
#ADDITION OF NUMPY ARRAYS
#axis 0 addition in columns
#axis 1 addition in rows

In [19]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])

In [20]:
np.sum([n1, n2])

100

In [21]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [22]:
np.sum([n1, n2], axis=1)

array([30, 70])

In [23]:
#BASIC ADDITION

In [24]:
import numpy as np
n1=np.array([10, 20, 30])
n1=n1+1
n1

array([11, 21, 31])

In [25]:
#BASIC SUBSTRACTION

In [26]:
import numpy as np
n1=np.array([10, 20, 30])
n1=n1-1
n1

array([ 9, 19, 29])

In [27]:
#BASIC MULTIPLICATION

In [28]:
import numpy as np
n1= np.array([10, 20, 30])
n1=n1*2
n1

array([20, 40, 60])

In [29]:
#BASIC DIVISION

In [30]:
import numpy as np
n1=np.array([10, 20, 30])
n1=n1/2
n1

array([ 5., 10., 15.])